### ISSUE TITLE
unrecognized command line option ‘-Wpedantic’

### ISSUE THREAD

**Issue by NeonHorizon** [DiJuMx/libpiglow#1]
I got the error during make install and fixed it by changing -Wpedantic to -pedantic in src/CMakeLists.txt
Not sure if this was the correct thing to do, I don't have much experience with C currently.

Full output below

root@test:~/libpiglow/build# make install
[100%] Building C object src/CMakeFiles/piglow.dir/libpiglow.c.o
cc1: error: unrecognized command line option ‘-Wpedantic’
src/CMakeFiles/piglow.dir/build.make:54: recipe for target 'src/CMakeFiles/piglow.dir/libpiglow.c.o' failed
make[2]: **\* [src/CMakeFiles/piglow.dir/libpiglow.c.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'src/CMakeFiles/piglow.dir/all' failed
make[1]: **\* [src/CMakeFiles/piglow.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by DiJuMx** [comment]
Okay, I've just checked online and it appears that `-Wpedantic` is not present in some versions of gcc, but `-pedantic` is.

I'll push a change later to fix.
