### ISSUE TITLE
piglow_set with a value of zero affects LED's on other arms

### ISSUE THREAD

**Issue by NeonHorizon** [DiJuMx/libpiglow#2]
This is a really great library, I've just noticed one peculiarity.
If you call for example:
piglow_set(TOP, RED, 0);
It also turns off the white LED on BOTTOM

**Comment by DiJuMx** [comment]
Is that the only LED that gets turned off?
And does it only happen when the value is 0?

**Comment by NeonHorizon** [comment]
It only happens when the value is zero. Basically when setting an LED on one arm it turns off an LED on another arm. I noticed it as I was writing a program that took an array of values and set every LED and when setting one of the arms to zero it wiped out one of the other arms.

**Comment by DiJuMx** [comment]
Should now be fixed in latest commit (ad159e2)
